# Generated by Django 4.2.4 on 2023-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainingzone', '0002_profesores_delete_entrenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='apellido',
            field=models.CharField(default='ValorPredeterminado', max_length=50),
        ),
    ]
