# Generated by Django 4.2.4 on 2023-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainingzone', '0003_profesores_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorados',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='Email',
        ),
        migrations.AddField(
            model_name='cursos',
            name='valor',
            field=models.CharField(default='ValorPredeterminado', max_length=50),
        ),
        migrations.AddField(
            model_name='suplementos',
            name='valor',
            field=models.CharField(default='ValorPredeterminado', max_length=50),
        ),
        migrations.AlterField(
            model_name='asesorados',
            name='Curso',
            field=models.CharField(default='ValorPredeterminado', max_length=50),
        ),
        migrations.AlterField(
            model_name='suplementos',
            name='Clase_de_suplemento',
            field=models.CharField(default='ValorPredeterminado', max_length=50),
        ),
        migrations.AddField(
            model_name='asesorados',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profesores',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
    ]
