# Generated by Django 4.2.4 on 2023-09-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainingzone', '0004_remove_asesorados_email_remove_profesores_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplementos',
            name='Clase_de_suplemento',
        ),
    ]
