# Generated by Django 4.2.4 on 2023-09-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainingzone', '0005_remove_suplementos_clase_de_suplemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorados',
            name='Curso',
        ),
    ]
